### ISSUE TITLE
switch to bss_eval_images?

### ISSUE THREAD

**Issue by ssfrr** [faroit/dsdtools#16]
Now that `mir_eval` supports `bss_eval_images`, would using it in the evaluation code here mean that people could reproduce the SiSEC evaluation without MATLAB? You mention in the README that the python results and MATLAB results don't match up, but I'm not sure if this is the only issue or if there are other problems.

**Comment by ssfrr** [comment]
oh, whoops, just noticed you're working on a 0.2.0 branch that incorporates the new `mir_eval` features. sorry for the noise.

**Comment by faroit** [comment]
no, no. It's fine. Thanks for the reminder. ;-)

I did not finish the 0.2.0 branch because we want to incorporate the other sisec tasks into this tool as well. For that reason we will rename/fork the tool end of this summer. It will also include baseline DNN based models, so users have a nice reference to start with.

The `bss_eval_images` was contributed to mir_eval from us, so we did make sure that it is compatible to the matlab results (off to roundings errors). 

We haven't decided on the evaluation model (aggregating the results), but I will do this in the open. Ideas and suggestions are of course highly welcome!
